sudo: false
language: python
#os: osx

python:
  - "3.8"

before_install:
  - sudo apt-get install libglfw3-dev libglfw3 libsdl2-dev libassimp-dev python-pyassimp xauth xvfb
  #- brew update
  #- brew install sdl2 glm minizip glew glfw glfw3 assimp python@3.8

install:
  - pip3 install -r requirements.txt

script:
  - xvfb-run -a python3 kuplung.py
