sudo: false

language: python

python:
  - "3.8"

before_install:
  - sudo apt-get install libglfw3-dev libglfw3 libsdl2-dev libassimp-dev python-pyassimp

install:
  - pip3 install -r requirements.txt

script:
  - python3 kuplung.py
